require("./clientmode/death")
require("./clientmode/PrettyTags")
require("./clientmode/reglog")
require("./clientmode/scoreboard")
require("./clientmode/statusBar")
require('./clientmode/dialogs')
require('./clientmode/chat')
require('./clientmode/audio3D')