require("./clientmode/death")
require("./clientmode/PrettyTags")
require("./clientmode/reglog")
require("./clientmode/scoreboard")
require("./clientmode/statusBar")
require('./clientmode/dialogs')
require('./clientmode/chat')
require('./clientmode/audio3D')
require('./clientmode/customRadio')
require('./clientmode/shot-tp')
require('./clientmode/anims')
require('./clientmode/3dtext')

//Disable ambient sounds
mp.game.audio.startAudioScene("CHARACTER_CHANGE_IN_SKY_SCENE")